theme: "just-the-docs"

exclude:
  - "*.pxm"
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

title: REMLA
description: >- # this means to ignore newlines until "baseurl:"
  Release Engineering for Machine Learning Applications (CS4295).
baseurl: "/remla" # the subpath of your site, e.g. /blog
url: "https://se.ewi.tudelft.nl/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title/

surfdrive_id: "207BTysNQFuVZPE" # the hash from a surfdrive link
surfdrive: "https://surfdrive.surf.nl/files/index.php/s/207BTysNQFuVZPE"

# OOPP Specific things ----------------------------------------------------------------------------------------
color_scheme: tudelft
logo: "assets/images/tudelft.png"
# Links that show in the top right
aux_links:
  "Brightspace":
    - "https://brightspace.tudelft.nl/d2l/home/499353"
  "Studyguide":
    - "https://studiegids.tudelft.nl/a101_displayCourse.do?course_id=61258"
aux_links_new_tab: false